"""Feature-system protocol definitions."""

from __future__ import annotations

from typing import Protocol


class FeatureSystem(Protocol):
    """Protocol all feature-system implementations must satisfy."""

    @property
    def name(self) -> str: ...

    def grapheme_to_features(self, grapheme: str) -> frozenset[str] | None: ...

    def features_to_grapheme(self, features: frozenset[str]) -> str | None: ...

    def is_class(self, grapheme: str) -> bool: ...

    def class_features(self, grapheme: str) -> frozenset[str] | None: ...

    def add_features(self, base: frozenset[str], added: frozenset[str]) -> frozenset[str]: ...

    def partial_match(self, pattern: frozenset[str], target: frozenset[str]) -> bool: ...

    def feature_distance(self, feat_a: str, feat_b: str) -> float: ...

    def sound_distance(self, feats_a: frozenset[str], feats_b: frozenset[str]) -> float: ...
